#ifndef YGVPAR_H
#define YGVPAR_H

#ifndef __T
#ifdef _NTDDK_
#define __T(x)      L ## x
#else
#define __T(x)      x
#endif /* _NTDDK_ */
#endif /* __T */

#ifndef _T
#define _T(x)       __T(x)
#endif

#ifndef GARBAGE
#define GARBAGE     0xcc
#endif

#define YGVPAR_VERSION_MAJOR	    2
#define YGVPAR_VERSION_MINOR	    0

#ifndef  DWORD
#define DWORD ULONG
#endif

#ifndef SECTOR_SIZE
#define SECTOR_SIZE             512
#endif
#define MAX_VPAR_DRIVE          4

#ifndef MAXIMUM_FILENAME_LENGTH
#define MAXIMUM_FILENAME_LENGTH 256
#endif

#define YGVPAR_DIR_NAME		_T("\\Device\\YGVPar")

#define IOCTL_YGVPAR_GET_VERSION \
	CTL_CODE(FILE_DEVICE_DISK, 0x900, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGVPAR_OPEN_MEDIA \
	CTL_CODE(FILE_DEVICE_DISK, 0x901, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGVPAR_CLOSE_MEDIA \
	CTL_CODE(FILE_DEVICE_DISK, 0x902, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGVPAR_SECTOR_GROUPS \
	CTL_CODE(FILE_DEVICE_DISK, 0x903, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGVPAR_UPDATE_FSDATA \
	CTL_CODE(FILE_DEVICE_DISK, 0x904, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGVPAR_SYSSEC_NUMBER \
	CTL_CODE(FILE_DEVICE_DISK, 0x905, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGVPAR_DRIVE_ISUSEFUL \
	CTL_CODE(FILE_DEVICE_DISK, 0x906, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGVPAR_ENABLE_DISABLE \
	CTL_CODE(FILE_DEVICE_DISK, 0x907, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGVPAR_FLUSH_MEDIA \
	CTL_CODE(FILE_DEVICE_DISK, 0x908, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGVPAR_READ_DISK \
	CTL_CODE(FILE_DEVICE_DISK, 0x90A, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGVPAR_WRITE_DISK \
	CTL_CODE(FILE_DEVICE_DISK, 0x90B, METHOD_BUFFERED, FILE_ANY_ACCESS)

#ifndef	DIOC_REG
#define	DIOC_REG

typedef struct DIOCRegs	{
	DWORD	reg_EBX;
	DWORD	reg_EDX;
	DWORD	reg_ECX;
	DWORD	reg_EAX;
	DWORD	reg_EDI;
	DWORD	reg_ESI;
	DWORD	reg_Flags;		
} DIOC_REGISTERS;

#endif

typedef struct _YGVPAR_PARAMETER {
	UCHAR                   btFileDrive;
	DISK_GEOMETRY           DiskGeometry;
	ULONG                   GeometryStatus;
    PARTITION_INFORMATION   PartitionInformation;
	ULONG                   ParInfoStatus;
	UCHAR					ucDriveLetter;
} YGVPAR_PARAMETER, *PYGVPAR_PARAMETER;


typedef struct _YGVPARRWPARAM
{
	ULONG	dwStartSec;
	ULONG	dwSectors;
	PVOID	pBuffer;
} YGVPARRWPARAM,*PYGVPARRWPARAM;

#endif /* YGVPAR_H */
