// YGDISKRW.H
// Copyright (C) 2007 by YG Corp.
// All rights reserved
// Author:  lihuibin
// Date:    27-Jun-2007

#ifndef YGDISKRW_EXPORT_H
#define YGDISKRW_EXPORT_H

#define YGDISKRW_VERSION_MAJOR	    2
#define YGDISKRW_VERSION_MINOR	    0

#pragma	pack(1)

typedef struct _YGDISKRWPARAM
{
	ULONG	ulDisk;
	ULONG	dwStartSec;
	ULONG	dwLength;
	PVOID	pBuffer;
} YGDISKRWPARAM,*PYGDISKRWPARAM;

#pragma	pack()

#define IOCTL_YGDISKRW_GET_VERSION \
	CTL_CODE(FILE_DEVICE_DISK, 0xF00, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGDISKRW_READ_DISK \
	CTL_CODE(FILE_DEVICE_DISK, 0xF01, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGDISKRW_WRITE_DISK \
	CTL_CODE(FILE_DEVICE_DISK, 0xF02, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGDISKRW_READ_DISK_KERNEL \
	CTL_CODE(FILE_DEVICE_DISK, 0xF03, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_YGDISKRW_WRITE_DISK_KERNEL \
	CTL_CODE(FILE_DEVICE_DISK, 0xF04, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif	//  YGDISKRW_EXPORT_H
