//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by E:\Products\DeleteMaster\Cur_ver\DelFile\Japanese\DelFile.rc
//
#define IDC_BACKUP_DELTE                3
#define ID_DEL_ITEM                     3
#define IDS_ABOUTBOX                    101
#define IDD_DELFILE_DIALOG              102
#define IDS_SINGLE_SELECTED             102
#define IDS_MULTY_SELECTED              103
#define IDS_DELETE_STATUS               104
#define IDS_DELETE_SUCCESS              105
#define IDS_00_METHOD                   106
#define IDS_FF_METHOD                   107
#define IDS_RANDOM_METHOD               108
#define IDS_NSA_METHOD                  109
#define IDS_OLD_NSA_METHOD              110
#define IDS_DOD_STD_METHOD              111
#define IDS_NATO_METHOD                 112
#define IDS_GUTMANN_METHOD              113
#define IDS_PRODUCT_NAME                114
#define IDS_NO_ENOUGH_MEM               115
#define IDS_SELECT_OTHER_SAVE_PATH      116
#define IDS_SELECT_PARENT_PATH          117
#define IDS_DEL_FINISH_CAPTION          118
#define IDS_DEVICE_NOT_READY            119
#define IDS_BACKUP_FILE_NAME            120
#define IDS_DELETED_FILES               121
#define IDS_DELETED_FILE_SIZE           122
#define IDS_DELETE_CONFIRM_ITEMS        123
#define IDS_DELETE_CONFIRM_ITEM         124
#define IDS_LOG_FORMAT                  125
#define IDS_RESULT_SUCC                 126
#define IDS_RESULT_FAIL                 127
#define IDR_MAINFRAME                   128
#define IDS_LOG_FAIL                    128
#define IDD_SELECT_METHOD               129
#define IDS_SELECT_TARGET               129
#define IDS_SEARCH                      129
#define IDD_DEL_PROGRESS                130
#define IDS_FOLDER                      130
#define IDD_GIVE_DIRECTORY              131
#define IDS_FILE_NAME                   131
#define IDB_TREE                        132
#define IDS_DIRECTORY                   132
#define IDD_SHREDDER                    133
#define IDS_FILE_SIZE                   133
#define IDD_SCHEDULE_EDIT               133
#define IDB_LIST                        134
#define IDS_LAST_MODIFY                 134
#define IDD_MAIN_DIALOG                 135
#define IDS_LAST_ACCESS                 135
#define IDD_FOLDER_FORM                 136
#define IDS_CREATE_TIME                 136
#define IDD_SEARCH_FORM                 137
#define IDS_NAME_VALID                  137
#define IDS_MIN                         138
#define IDR_MAINMENU                    139
#define IDS_MAX                         139
#define IDS_ALL_TYPE                    140
#define IDS_UNKNOWN_TYPE                141
#define IDR_TOOLBAR                     142
#define IDS_DATE_ERROR                  142
#define IDS_CANCEL_SEARCH               143
#define IDS_SEARCH2                     144
#define IDD_SCHEDULE                    144
#define IDS_NO_TIMESTAMP                145
#define IDS_NO_ITEM                     145
#define IDD_DIALOG_LOGIN                145
#define IDS_INSUFER_MEMORY              146
#define IDS_NO_FILE_SELECTED            147
#define IDS_CREATE_DIR_FAIL             148
#define IDS_OVER_WRITE                  149
#define IDS_CREATE_FILE_FAIL            150
#define IDS_STRING151                   151
#define IDS_INVALID_PATH                151
#define IDS_DELETE_TIME                 153
#define IDS_EMPTY_NAME                  154
#define IDS_DELETE_DATE                 155
#define IDS_SUNDAY                      156
#define IDS_MONDAY                      157
#define IDS_TUESDAY                     158
#define IDS_WEDNESDAY                   159
#define IDS_THURSDAY                    160
#define IDS_FRIDAY                      161
#define IDS_SATURDAY                    162
#define IDS_DAY_OF_MONTH                163
#define IDS_UNKNOW                      164
#define IDS_SELECT_SCHEDULE             165
#define IDS_SELECT_FILE_OR_DIR          166
#define IDS_INVALID_DATE                167
#define IDS_PROTECT_PATH                168
#define IDS_TRY_LIMIT                   169
#define IDS_PASSWORD_MATCH              170
#define IDS_INVALID_PASSWORD            171
#define IDS_ENTER_PASS                  172
#define IDS_NEW_PASSWORD                172
#define IDS_NEW_PASS                    173
#define IDS_ENTER_PASSWORD              173
#define IDS_RECYCLED                    174
#define IDC_COMBO1                      1000
#define IDC_FILE_TOSEARCH               1000
#define IDC_COMBO_WEEK                  1000
#define IDC_SEL_ITEM                    1002
#define IDC_COMBO_TIMESTAMP             1002
#define IDC_COMBO_PATH                  1002
#define IDC_DEL_STATUS                  1003
#define IDC_COMBO_DATE_TYPE             1003
#define IDC_DEL_PROGRESS                1004
#define IDC_CHECK_DATE                  1004
#define IDC_DELETE_METHOD               1005
#define IDC_BACK_FILE_NAME              1005
#define IDC_FILE                        1006
#define IDC_DATETIMEPICKER_START        1006
#define IDC_TREE                        1007
#define IDC_DATETIMEPICKER_END          1007
#define IDC_DEL_LIST                    1008
#define IDC_CHECK_TYPE                  1008
#define IDC_SCHEDULE_LIST               1008
#define IDC_BUTTON_SEL_ALL              1010
#define IDC_COMBO_FILE_TYPE             1010
#define IDC_DEL_STRING                  1011
#define IDC_CHECK_SIZE                  1011
#define IDC_BEEP_OFF                    1012
#define IDC_COMBO_SIZE_TYPE             1012
#define IDC_FILE_SIZE                   1013
#define IDC_FILE_LIST                   1014
#define IDC_ADD_SCHEDULE                1015
#define IDC_SPIN_SIZE                   1016
#define IDC_DELETE_SCHEDULE             1016
#define IDC_SEARCH                      1017
#define IDC_MODIFY_SCHEDULE             1017
#define IDC_CLOSE_DIALOG                1018
#define IDC_FILE_PATH                   1019
#define IDC_REFER                       1020
#define IDC_RADIO1                      1021
#define IDC_RADIO2                      1022
#define IDC_COMBO_MONTH                 1023
#define IDC_DATETIMEPICKER1             1024
#define IDC_COMBO_METHOD                1025
#define IDC_CHECK_LOG                   1026
#define IDC_PASSWORD                    1034
#define IDC_PASSWORD_CONFIRM            1035
#define IDC_CONFIRM_PASS                1036
#define IDC_SET_PASSWORD                1037
#define IDC_OLD_PASSWORD                1038
#define IDC_OLD_PASS                    1039
#define IDC_ENTER_PASS                  1042
#define IDC_RADIO_DELETE_RECYCLE        1043
#define IDC_RADIO_DELETE_FILE           1044
#define ID_SEC_DELETE                   32771
#define ID_FOLDER_VIEW                  32772
#define ID_SEARCH_VIEW                  32773
#define ID_EXIT                         32774
#define ID_SCHEDULE_EDIT                32779
#define ID_BUTTON32780                  32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
