//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by c:\source\trunk\work\trunk\Products\FileBackup\Uni_ver\UI\Japanese\AM01.rc
//
#define IDS_SETTING_NAME_TITLE          1
#define IDS_SETTING_NAME_SUBTITLE       2
#define IDS_BACKUP_TYPE_TITLE           3
#define IDS_BACKUP_TYPE_SUBTITLE        4
#define IDS_BACKUP_SOURCE_TITLE         5
#define IDS_TOOLTIP                     6
#define IDS_BACKUP_SOURCE_SUBTITLE      7
#define IDS_BACKUP_DEST_TITLE           8
#define IDS_BACKUP_DEST_SUBTITLE        9
#define IDS_SETTING_WIZARD              10
#define IDS_SETUP                       11
#define IDS_SOURCE                      12
#define IDS_SELECT_FILE                 13
#define IDS_TITLE                       14
#define IDS_DISK_NOTREADY               15
#define IDS_ERROR                       16
#define IDS_BUILD_ISO9660               17
#define IDS_CLOSE_SESSION               18
#define IDS_RECORD_GAP                  19
#define IDS_RECORD_TRACK                20
#define IDS_RECORD_USERDATA             21
#define IDS_NOT_WRITEABLE               22
#define IDS_NO_CDR                      23
#define IDS_BUILDISO_FAIL               24
#define IDS_INSUFFER_SPACE              25
#define IDS_FILE_NOTFOUND               26
#define IDS_SETTING_TITLE               27
#define IDS_SETTING_NAME_EMPTY          28
#define IDS_SOURCE_EMPTY                29
#define IDS_TARGET_EMPTY                30
#define IDS_SOURCE_IMGEMPTY             31
#define IDS_ABOUT_NAME                  32
#define IDS_ABOUT_COMPANY               33
#define IDS_ABOUT_SERIALNUM             34
#define IDS_INVALID_IMAGE               35
#define IDS_FAILER_SET_CURRENT          36
#define IDS_INVALID_SOURCE              37
#define IDS_CONFLICT                    38
#define IDS_BACKUP_RUNING               39
#define IDS_NOT_LAST_IMAGE              40
#define IDS_OPEN_IMAGE_FAIL             41
#define IDS_NOT_ENOUGH_SPACE            42
#define IDS_RECORD_CDR_ERROR            43
#define IDS_SETTING_NAME_EXIST          44
#define IDS_NEXT_CD                     45
#define IDS_MAIL_DATA_NOT_READY         46
#define IDS_NO_SETTING_SELECTED         47
#define IDS_MONDAY                      48
#define IDS_TUESDAY                     49
#define IDS_WEDNESDAY                   50
#define IDS_THURSDAY                    51
#define IDS_FRIDAY                      52
#define IDS_SATURDAY                    53
#define IDS_SUNDAY                      54
#define IDS_DAY_OF_WEEK                 55
#define IDS_DATE_OF_MONTH               56
#define IDS_BASE_BACKUP                 57
#define IDS_EVERY_WEEK                  59
#define IDS_EVERY_MONTH                 60
#define IDS_ON                          61
#define IDS_AT                          62
#define IDS_DIFF_BACKUP                 66
#define IDS_SHUTDOWN_COMPUTER           67
#define IDS_DO_NOT_SHUTDOWN             68
#define IDS_DATE                        69
#define IDS_SAME_SETTING_NAME           70
#define IDS_CHANGE_SETTING_NAME         71
#define IDS_ASK                         72
#define IDS_NO_CURRENT_SETTING          73
#define IDS_PASSWORD_NOT_MATCH          74
#define IDS_SELECT_MAIL_CLIENT          75
#define IDS_YES                         76
#define IDS_NO                          77
#define IDS_MAX_PASSWORD                78
#define IDD_AMABOUT                     101
#define IDD_AMRESTORE                   102
#define IDD_AMBACKUP                    103
#define IDD_AMSETTING                   104
#define IDD_AMTASK                      106
#define IDD_WZSTEP1                     116
#define IDD_WZSTEP2                     117
#define IDD_WZSTEP3                     118
#define IDD_WZSTEP4                     119
#define ID_MAIN_CONTROL                 150
#define ID_SEARCH                       151
#define ID_ABOUT                        152
#define ID_BACKUP_SHUTDOWN              153
#define IDS_EXCUTE_TIME                 153
#define ID_REMBER_SETTING               154
#define ID_SET_CURRENT                  155
#define IDS_EXCUTE_DATE                 155
#define IDS_SHUTDOWN                    156
#define ID_NEW_BACKUP                   157
#define ID_RESTORE                      158
#define IDS_DAY_OF_MONTH                163
#define IDS_UNKNOW                      164
#define IDS_SELECT_SCHEDULE             165
#define IDS_SCHEDULE_EXIST              166
#define IDS_INVALID_TIME                167
#define IDS_FULL_BACKUP                 168
#define IDS_INCREMENTAL_BACKUP          169
#define IDS_COMBINATION_BACKUP          170
#define IDS_WINDOWS_MAIL                171
#define IDS_OUTLOOK_EXPRESS             172
#define IDI_ICON_MAIN                   206
#define IDR_MAINMENU                    207
#define IDC_ARROW_NORMAL                248
#define IDC_INFORMATION                 250
#define IDC_SETTING_NAME                251
#define IDB_STATEICONS                  272
#define IDB_WATERMARK                   273
#define IDD_MAKE_CDR                    274
#define IDD_SAVE_SETTING                275
#define IDD_BACKUP_STATE                276
#define IDR_FILE_COPY                   277
#define IDB_SPLASH                      278
#define IDD_VIEW_SETTING                281
#define IDD_EASY_WIZARD_1               283
#define IDD_EASY_WIZARD_2               284
#define IDD_EASY_WIZARD_3               285
#define IDD_SQUEEZE_IMAGE               286
#define IDD_SQUEEZE_STATE               287
#define IDD_DIALOG_SHUTDOWN             288
#define IDD_ADVANCED_SCHEDULE           289
#define IDD_SCHEDULE_PAGE_1             290
#define IDD_SCHEDULE_PAGE_2             291
#define IDD_SCHEDULE_PAGE_3             292
#define IDD_SCHEDULE_RESULT             293
#define IDD_SET_PASSWORD                294
#define IDD_REENTER_PASSWORD            296
#define IDD_SCHEDULE_EDIT               298
#define IDC_SCHEDULE_LIST               1008
#define IDC_ADD_SCHEDULE                1015
#define IDC_DELETE_SCHEDULE             1016
#define IDC_RADIO1                      1179
#define IDC_RADIO2                      1180
#define IDC_RADIO3                      1181
#define IDC_EDIT_DIRECTORY              1182
#define IDC_LIST1                       1183
#define IDC_REFER                       1184
#define IDC_ADD                         1185
#define IDC_REMOVE                      1186
#define IDC_TXT_INDIVALDIR              1188
#define IDC_TXT_SOURCE_DIR              1189
#define IDC_EDIT1                       1193
#define IDC_REFER_IMAGE                 1194
#define IDC_TXT_IMAGE                   1195
#define IDC_TXT_MAIL_CLIENT             1196
#define IDC_BUTTON1                     1200
#define IDC_BUTTON_SEPERATE_FILE        1200
#define IDC_BUTTON_PREPARE_RM           1200
#define IDC_BUTTON_CANCEL               1200
#define IDC_BUTTON_GET_ONE_FILE         1200
#define IDC_BUTTON_OEPath               1200
#define IDC_BUTTON_OE_PATH              1200
#define IDC_BUTTON_VIEW_SETTING         1200
#define IDC_BUTTON_EXIT                 1200
#define IDC_BUTTON_REFER                1200
#define IDC_BUTTON_SAVE_SCHEDULE        1200
#define IDC_BUTTON_SQUEEZE_IMAGE        1200
#define IDC_BUTTON_CANCLE               1200
#define IDC_BUTTON_YES                  1200
#define IDC_ENCRYPT                     1200
#define IDC_SET_PASSWORD_CANCEL         1200
#define IDC_REENTER_PASSWORD_CANCEL     1200
#define IDC_SET_PASSWORD                1200
#define IDC_SET_PASS                    1200
#define IDC_BUTTON_CLOSE                1200
#define IDC_IMAGE_PATH                  1201
#define IDC_EXECUTE                     1203
#define IDC_SETTING_WIZ                 1204
#define IDC_COMMENT                     1205
#define IDC_BUTTON_FILE                 1206
#define IDC_CURRENT_SETTING             1206
#define IDC_IMAGE_FILE_NAME             1207
#define IDC_CURRENT                     1207
#define IDC_BUTTON_CREATE               1208
#define IDC_PROGRESS1                   1209
#define IDC_STATE                       1210
#define IDC_SAVE_SETTING                1213
#define IDC_START                       1214
#define IDC_TARGET_PATH                 1215
#define IDC_REFER_TARGET                1216
#define IDC_REFER_SOURCE                1217
#define IDC_SOURCE_PATH                 1218
#define IDC_CHECK1                      1221
#define IDC_CHECK2                      1222
#define IDC_CHECK3                      1223
#define IDC_CHECK4                      1224
#define IDC_CHECK5                      1225
#define IDC_CHECK6                      1226
#define IDC_CHECK7                      1227
#define IDC_DATETIMEPICKER2             1228
#define IDC_DATETIMEPICKER3             1229
#define IDC_DATETIMEPICKER4             1230
#define IDC_DATETIMEPICKER5             1231
#define IDC_DATETIMEPICKER6             1232
#define IDC_DATETIMEPICKER7             1233
#define IDC_DATETIMEPICKER8             1234
#define IDC_COMBO1                      1235
#define IDC_COMBO_DATE                  1235
#define IDC_CURRENT_FILE                1236
#define IDC_ANIMATE1                    1237
#define IDC_BUTTON_DIFF_RM              1238
#define IDC_EDIT_TARGET                 1239
#define IDC_BUTTON_CHANGE_NAME          1240
#define IDC_EDIT_SETTING_NAME           1241
#define IDC_LIST_SOURCE                 1242
#define IDC_STATIC_SETTING_NAME         1243
#define IDC_EDIT_TARGET_FILE            1246
#define IDC_LIST_SOURCE_FILE            1247
#define IDC_BUTTON2                     1251
#define IDC_BUTTON_TEST_LIST            1251
#define IDC_BUTTON_TEST_SOURCE          1251
#define IDC_BUTTON_EASY_BACKUP          1251
#define IDC_BUTTON_MODIFY_SCHEDULE      1251
#define IDC_BUTTON_REFER_TARGET         1251
#define IDC_BUTTON_QUIT                 1251
#define IDC_BUTTON_NO                   1251
#define IDC_SET_PASSWORD_OK             1251
#define IDC_REENTER_PASSWORD_OK         1251
#define IDC_BUTTON_TEST                 1251
#define IDC_RADIO_MY_DOCUMENT           1252
#define IDC_RADIO_MY_MAIL               1253
#define IDC_RADIO_DOCUMENT_MAIL         1254
#define IDC_RADIO_OUTLOOK_EXPRESS       1255
#define IDC_RADIO_OUTLOOK               1256
#define IDC_RADIO_THE_BECKY             1257
#define IDC_LIST_SETTING_NAME           1258
#define IDC_EDIT_SOURCE_IMAGE           1259
#define IDC_BUTTON_REFER_SOURCE         1260
#define IDC_EDIT_TARGET_IMAGE           1261
#define IDC_ANIMATE_SQUEEZE_FILE        1267
#define IDC_SQUEEZE_PROGRESS            1268
#define IDC_CHECK_SHUT_MONDAY           1271
#define IDC_CHECK_SHUT_TUESDAY          1272
#define IDC_CHECK_SHUT_WEDNESDAY        1273
#define IDC_CHECK_SHUT_THURSDAY         1274
#define IDC_CHECK_SHUT_FRIDAY           1275
#define IDC_CHECK_SHUT_SATURDAY         1276
#define IDC_CHECK_SHUT_SUNDAY           1277
#define IDC_STATIC_LEFT_SECOND          1278
#define IDC_PROGRESS_TIME               1279
#define IDC_CHECK10                     1282
#define IDC_CHECK11                     1283
#define IDC_CHECK12                     1284
#define IDC_CHECK13                     1285
#define IDC_CHECK14                     1286
#define IDC_BUTTON_SNAPSHOT             1287
#define IDC_BUTTON_ADVANCED_SCHEDULE    1289
#define IDC_SETTING_LIST                1290
#define IDC_DATETIMEPICKER1             1298
#define IDC_BACKUP_TIME                 1298
#define IDC_DATE_TITLE                  1299
#define IDC_SHUTDOWN_OPTION             1300
#define IDC_BACKUP_PERIOD               1301
#define IDC_BUTTON_CANCEL_SCHEDULE      1302
#define IDC_STATIC_BASE_BACKUP          1303
#define IDC_STATIC_DIFF_BACKUP          1304
#define IDC_STATIC_SHUTDOWN_OPTION      1305
#define IDC_PASSWORD                    1306
#define IDC_VIEW_SETTING_ENCRYPT        1307
#define IDC_LOG_FAIL                    1308
#define IDC_RETRY                       1310
#define IDC_MINUTES                     1311
#define IDC_AUTO_SPAWN                  1312
#define IDC_BACKUP_TYPE                 1315
#define IDC_CONFIRM_PASSWORD            1316
#define IDC_RADIO4                      1317
#define ID_CLOSE                        32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        299
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1318
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
