@md backup
@xcopy .\cur_ver\*.dsw .\backup/s/y
@xcopy .\cur_ver\*.dsp .\backup/s/y
@xcopy .\cur_ver\*.asm .\backup/s/y
@xcopy .\cur_ver\*.inc .\backup/s/y
@xcopy .\cur_ver\*.mak .\backup/s/y
@xcopy .\cur_ver\*.cpp .\backup/s/y
@xcopy .\cur_ver\*.makefile .\backup/s/y
@xcopy .\cur_ver\*.c .\backup/s/y
@xcopy .\cur_ver\*.rc .\backup/s/y
@xcopy .\cur_ver\*.h .\backup/s/y
@xcopy .\cur_ver\*.def .\backup/s/y
