//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by c:\source\Products\DeleteMaster\Uni_ver\WinUI\2000\Japanese\DeleteMaster.rc
//
#define IDC_NO_SAVE                     3
#define IDS_DM_ERROR                    100
#define IDS_APP_INIT_ERR                101
#define IDS_NOT_ADMIN                   102
#define IDS_VOLUME_LABEL                103
#define IDS_TYPE                        104
#define IDS_SIZE                        105
#define IDS_USED                        106
#define IDS_UNUSED                      107
#define IDS_STATUS                      108
#define IDS_ORI_LOG                     109
#define IDS_HIDE_FAT32                  110
#define IDS_FAT32                       111
#define IDS_FAT                         112
#define IDS_HIDE_FAT                    113
#define IDS_NTFS                        114
#define IDS_HIDE_NTFS                   115
#define IDS_LUX_EXT2                    116
#define IDS_LUX_SWP                     117
#define IDS_FREE                        118
#define IDS_LIST_ACTIVE                 119
#define IDS_LIST_INACTIVE               120
#define IDS_LIST_LOG                    121
#define IDS_LIST_PRI                    122
#define IDS_UNKNOW                      123
#define IDS_NOT_DELETE_SYSTEM_PAR       124
#define IDS_CHS                         125
#define IDS_SECTOR_RANGE                126
#define IDS_CONFIRM_DISK                127
#define IDS_CONFIRM_PARTITION           128
#define IDS_METHOD                      129
#define IDR_MAINFRAME                   130
#define IDS_DEL_PERSENT                 130
#define IDD_DM_DELETE_PARTITION         131
#define IDS_DEL_PROGRESS_MOTHED         131
#define IDD_DM_DISK_VIEW                132
#define IDS_PRODUCT_NAME                132
#define IDB_TAB_IMAGE_LIST              133
#define IDS_00_MOTHED                   133
#define IDB_BOX                         134
#define IDS_FF_MOTHED                   134
#define IDB_LIST                        135
#define IDS_RANDOM_MOTHED               135
#define IDD_VIEW_SECTOR                 136
#define IDS_NSA_MOTHED                  136
#define IDS_OLD_NSA_MOTHED              137
#define IDD_SET_SERCTOR_NUMBER          138
#define IDS_DOD_STD_MOTHED              138
#define IDD_DELETE_CONFIRM              139
#define IDS_NATO_MOTHED                 139
#define IDD_DELETE_PROGRESS             140
#define IDS_GUTMANN_MOTHED              140
#define IDS_TIME_STAMP                  141
#define IDS_DELETE_PARTITION_REPORT     142
#define IDS_DELETE_DISK_REPORT          143
#define IDD_HARD_DISK_INFORMATION       143
#define IDS_USED_MOTHED                 144
#define IDD_DM_WIPE_FREE_SPACE          144
#define IDS_JAN                         145
#define IDD_WIPE_PROGRESS               145
#define IDS_FEB                         146
#define IDD_DELETE_OPTIONS              146
#define IDS_MAR                         147
#define IDS_APR                         148
#define IDS_MAY                         149
#define IDS_JUN                         150
#define IDS_JUL                         151
#define IDS_AUG                         152
#define IDS_SEP                         153
#define IDS_OCT                         154
#define IDS_NOV                         155
#define IDS_DEC                         156
#define IDS_DISK_LIST_FORMAT            157
#define IDS_FD_LIST_FORMAT              158
#define IDS_FD_NOT_READY                159
#define IDS_CONFIRM_FD                  160
#define IDS_DELETE_FD_REPORT            161
#define IDS_REMOVE_DISK_LIST            162
#define IDS_CONFIRM_RD                  163
#define IDS_MAIN_BUTTON_EXIT            164
#define IDS_DELETE_DELETE_PAR_FAIL      165
#define IDS_DEL_SUCCESS                 166
#define IDS_WRITE_SEC_FAIL              167
#define IDS_CONFIRM_WIPE_FREE           168
#define IDS_DM_CONFIRM_CAPTITION        169
#define IDS_TIME_INFO                   170
#define IDS_WIPE_FREE                   171
#define IDS_Q_FORMAT_PARTITION          172
#define IDS_DM_INFO                     173
#define IDS_WIPE_PARTITION_REPORT       174
#define IDS_DISKINFO_MODULE             175
#define IDS_DISKINFO_FIRMWARE_VER       176
#define IDS_DISKINFO_SERIAL_NUM         177
#define IDS_DISKINFO_CAPACITY           178
#define IDS_VERIFY_FAIL_WRAN_MSG        179
#define IDS_VERIFY_LOG                  180
#define IDS_SHREDDER_LINK               181
#define IDS_WRITE_LOG                   182
#define IDC_DM_DELETE_PAR_LIST          1001
#define IDC_DELETE_ENTIR_DISK           1002
#define IDC_DM_DELETE                   1004
#define IDC_DELETE_CLEAR                1005
#define IDC_DM_DISK_INFO                1006
#define IDC_DM_OPTIONS                  1007
#define IDC_DELETE_DISK_COMBO           1011
#define IDC_VIEW_DISK_COMBO             1012
#define IDC_VIEW_ENTIR_DISK             1013
#define IDC_DM_VIEW_PAR_LIST            1015
#define IDC_DM_VIEW                     1016
#define IDC_VIEW_CLEAR                  1017
#define IDC_SECTOR_INFOR_WIN            1017
#define IDC_CUSTOM1                     1019
#define IDC_SECTOR_NEXT                 1021
#define IDC_SECTOR_PREV                 1022
#define IDC_SET_SECTOR_NUM              1023
#define IDC_SECTOR_CHS                  1024
#define IDC_SECTOR_NUM                  1025
#define IDC_SECTOR_NUMBER               1026
#define IDC_SECTOR_RANGE                1028
#define IDC_SELECT_TARGET               1029
#define IDC_DEL_MOTHED                  1030
#define IDC_DELETE_PROGRESS             1031
#define IDC_COMPLETE_PECNET             1032
#define IDC_DEL_PROGRESS_TAR            1033
#define IDC_DEL_PROGRESS_MOTHED         1034
#define IDC_DELETE_MOTHED               1036
#define IDC_LABEL_MOTHED                1037
#define IDC_SAVE                        1039
#define IDC_MODULE_NUMBER               1040
#define IDC_FIRMWARE                    1041
#define IDC_SERIAL_NUMBER               1042
#define IDC_CAPACITY                    1043
#define IDC_WIPE_PAR_LIST               1045
#define IDC_DM_WIPE                     1048
#define IDC_WIPE_CLEAR                  1049
#define IDC_WIPE_DISK_COMBO             1050
#define IDC_WIPE_MOTHED                 1051
#define IDC_TIME_ELASPED                1052
#define IDC_TIME_REMAINING              1053
#define DC_WIPE_PROGRESS_TAR            1054
#define IDC_WIPE_PROGRESS_MOTHED        1055
#define IDC_WIPE_PROGRESS               1056
#define IDC_CHECK_SHREDDER              1059
#define IDC_OPTIONS_FORMAT              1060
#define IDC_OPTIONS_VERIFY              1061
#define IDC_SILENCE                     1062
#define IDC_BEEP_OFF                    1062
#define IDC_SLIENCE                     1063
#define IDC_TRY_NUM                     1068
#define IDCANCELWIPE                    1069

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
